name: Docker Image CI - HTML

on:
  push:
    branches: [ "main" ]
    paths:
    - 'html/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'html/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/krupanszkymarcell/html:0.1
        docker login ghcr.io -u krupanszkymarcell -p ${{secrets.ghcrtoken}}
        docker push ghcr.io/krupanszkymarcell/html:0.1
        
