name: HTML - Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]
    paths:
      - 'html/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'html/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4    
    
    - name: Build the Docker image
      run: |
        cd html
        docker build . --file Dockerfile --tag cr.jedlik.cloud/html-Krupanszky-Marcell:0.1             
        docker push cr.jedlik.cloud/html-Krupanszky-Marcell:0.1
