name: Docker Image CI - HTML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build ../html --file Dockerfile --tag cr.jedlik.cloud/html_krupanszky:0.1
        docker push cr.jedlik.cloud/html_krupanszky:0.1
        
